### ISSUE TITLE
isready ?

### ISSUE THREAD

**Issue by tissatussa** [Algorhythm-sxv/CriNNge#1]
hi, your Cheers README tells us that you started coding this CriNNge engine. I compiled the current source without errors (using command `cargo b -r`) but the binary doesn't function. I guess this project is in an early stage .. can you tell us something about the setup and progress ?

**Comment by Algorhythm-sxv** [comment]
Hi there! CriNNge is not currently a chess engine per se, it doesn't even have a search function yet! I would recommend waiting until I make a GitHub release, which may take a couple of months while I get it up to a standard I'm happy with.

Writing search is next on the horizon, after which I will complete the UCI implementation to facilitate progression tests.
